# -*- coding: utf-8 -*-
"""TicketCounterSystem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrkwjvu0BozwTAd7RlrEVeL9jt9Xv3WZ

tut [4]

Member1: Ali Sherif [16002370]

Member2: Kareem Hany[16003513]

Member3: Mostafa Elsheehy[16003976]
"""

import threading
import random
import time

TOTAL_SEATS = 300

global_available_seats = TOTAL_SEATS
global_booked_seats = 0
global_cancelled_seats = 0

audit_log = []

lock = threading.Lock()

def counter_worker(counter_id):

    for round_id in range(1, 6):

        print(f"\nCounter {counter_id} preparing Round {round_id} local operations...")

        local_view = global_available_seats

        print(f"-> Counter {counter_id}, Round {round_id}, reads global seats: {local_view} (may be stale)")

        local_queue = []

        num_operations = random.randint(3, 6)

        for _ in range(num_operations):

            operation = random.choice(["book", "cancel"])
            seats = random.randint(1, 20)

            local_queue.append((operation, seats))

        print(f"Local Queue: {local_queue}")

def counter_worker(counter_id):

    global global_available_seats
    global global_booked_seats
    global global_cancelled_seats

    for round_id in range(1, 6):

        print(f"\nCounter {counter_id} preparing Round {round_id} local operations...")

        local_view = global_available_seats

        print(f"-> Counter {counter_id}, Round {round_id}, reads global seats: {local_view} (may be stale)")


        local_queue = []

        num_operations = random.randint(3, 6)

        for _ in range(num_operations):

            operation = random.choice(["book", "cancel"])
            seats = random.randint(1, 20)

            local_queue.append((operation, seats))

        print(f"Local Queue: {local_queue}")


        time.sleep(random.uniform(0.5, 1.5))


        with lock:

            print(f"\n[SYNC - S] Counter {counter_id} syncing Round {round_id}...")

            applied_bookings = 0
            applied_cancellations = 0
            rejected_bookings = 0


            for operation, seats in local_queue:

                if operation == "book":


                    if seats <= global_available_seats:

                        global_available_seats -= seats
                        global_booked_seats += seats
                        applied_bookings += seats

                    else:

                        rejected_bookings += seats

                elif operation == "cancel":

                    global_available_seats += seats
                    global_cancelled_seats += seats
                    applied_cancellations += seats


            audit_log.append({
                "counter": counter_id,
                "round": round_id,
                "booked": applied_bookings,
                "cancelled": applied_cancellations,
                "rejected": rejected_bookings,
                "remaining": global_available_seats
            })

            print(f"[SYNC - S] Applied bookings: {applied_bookings}")
            print(f"[SYNC - S] Applied cancellations: {applied_cancellations}")
            print(f"[SYNC - S] Rejected bookings: {rejected_bookings}")
            print(f"[SYNC - S] Global seats after sync: {global_available_seats}")

threads = []

for counter_id in range(1, 5):

    t = threading.Thread(target=counter_worker, args=(counter_id,))
    threads.append(t)
    t.start()

for t in threads:
    t.join()

expected_available = (
    TOTAL_SEATS
    - global_booked_seats
    + global_cancelled_seats
)

print("\n=FINAL REPORT=")

print(f"Initial seats: {TOTAL_SEATS}")
print(f"Total booked seats (applied): {global_booked_seats}")
print(f"Total cancelled seats (applied): {global_cancelled_seats}")
print(f"Final global available seats: {global_available_seats}")

print(f"Expected available seats from invariant: {expected_available}")

if expected_available == global_available_seats:
    print("Invariant check: PASS")
else:
    print("Invariant check: FAIL")

